import { computeMLPrediction, computeSAHPScore, computeDecision } from './scoringEngine';

// Sample patients with realistic medical data
const rawSamplePatients = [
  {
    id: 'PT-001',
    name: 'Ananya Sharma',
    age: 45,
    gender: 'Female',
    bloodGroup: 'O+',
    organNeeded: 'Kidney',
    medicalUrgency: 9,
    diseaseSeverity: 8,
    waitingTime: 36,
    compatibilityScore: 85,
    survivalProbability: 72,
    comorbidities: 2,
    organFailureStage: 4,
    infectionRisk: 'Low',
    recoveryChance: 68,
    icuRequirement: 'Yes',
    donorMatchAvailability: 'High',
    bmi: 24.5,
    hemoglobin: 11.2,
    creatinine: 5.8,
    bloodPressure: '150/95',
    oxygenSaturation: 94,
  },
  {
    id: 'PT-002',
    name: 'Rajesh Kumar',
    age: 58,
    gender: 'Male',
    bloodGroup: 'A+',
    organNeeded: 'Liver',
    medicalUrgency: 7,
    diseaseSeverity: 7,
    waitingTime: 18,
    compatibilityScore: 72,
    survivalProbability: 65,
    comorbidities: 3,
    organFailureStage: 3,
    infectionRisk: 'Medium',
    recoveryChance: 55,
    icuRequirement: 'No',
    donorMatchAvailability: 'Medium',
    bmi: 27.3,
    hemoglobin: 10.5,
    creatinine: 2.1,
    bloodPressure: '140/90',
    oxygenSaturation: 96,
  },
  {
    id: 'PT-003',
    name: 'Priya Patel',
    age: 34,
    gender: 'Female',
    bloodGroup: 'B+',
    organNeeded: 'Heart',
    medicalUrgency: 10,
    diseaseSeverity: 9,
    waitingTime: 12,
    compatibilityScore: 90,
    survivalProbability: 78,
    comorbidities: 1,
    organFailureStage: 5,
    infectionRisk: 'Low',
    recoveryChance: 75,
    icuRequirement: 'Yes',
    donorMatchAvailability: 'High',
    bmi: 22.1,
    hemoglobin: 12.8,
    creatinine: 1.1,
    bloodPressure: '130/85',
    oxygenSaturation: 91,
  },
  {
    id: 'PT-004',
    name: 'Mohammed Ali',
    age: 62,
    gender: 'Male',
    bloodGroup: 'AB+',
    organNeeded: 'Lung',
    medicalUrgency: 6,
    diseaseSeverity: 5,
    waitingTime: 8,
    compatibilityScore: 60,
    survivalProbability: 58,
    comorbidities: 4,
    organFailureStage: 3,
    infectionRisk: 'High',
    recoveryChance: 42,
    icuRequirement: 'No',
    donorMatchAvailability: 'Low',
    bmi: 30.2,
    hemoglobin: 9.8,
    creatinine: 1.8,
    bloodPressure: '160/100',
    oxygenSaturation: 88,
  },
  {
    id: 'PT-005',
    name: 'Sneha Reddy',
    age: 29,
    gender: 'Female',
    bloodGroup: 'O-',
    organNeeded: 'Kidney',
    medicalUrgency: 4,
    diseaseSeverity: 4,
    waitingTime: 6,
    compatibilityScore: 78,
    survivalProbability: 88,
    comorbidities: 0,
    organFailureStage: 2,
    infectionRisk: 'Low',
    recoveryChance: 85,
    icuRequirement: 'No',
    donorMatchAvailability: 'Medium',
    bmi: 21.0,
    hemoglobin: 13.5,
    creatinine: 3.2,
    bloodPressure: '120/80',
    oxygenSaturation: 98,
  },
  {
    id: 'PT-006',
    name: 'Vikram Singh',
    age: 51,
    gender: 'Male',
    bloodGroup: 'A-',
    organNeeded: 'Liver',
    medicalUrgency: 8,
    diseaseSeverity: 8,
    waitingTime: 24,
    compatibilityScore: 68,
    survivalProbability: 55,
    comorbidities: 3,
    organFailureStage: 4,
    infectionRisk: 'Medium',
    recoveryChance: 48,
    icuRequirement: 'Yes',
    donorMatchAvailability: 'Medium',
    bmi: 26.8,
    hemoglobin: 10.2,
    creatinine: 2.5,
    bloodPressure: '145/92',
    oxygenSaturation: 93,
  },
  {
    id: 'PT-007',
    name: 'Deepa Nair',
    age: 41,
    gender: 'Female',
    bloodGroup: 'B-',
    organNeeded: 'Heart',
    medicalUrgency: 5,
    diseaseSeverity: 6,
    waitingTime: 14,
    compatibilityScore: 82,
    survivalProbability: 70,
    comorbidities: 1,
    organFailureStage: 2,
    infectionRisk: 'Low',
    recoveryChance: 72,
    icuRequirement: 'No',
    donorMatchAvailability: 'High',
    bmi: 23.4,
    hemoglobin: 12.0,
    creatinine: 1.0,
    bloodPressure: '125/82',
    oxygenSaturation: 97,
  },
  {
    id: 'PT-008',
    name: 'Arjun Menon',
    age: 67,
    gender: 'Male',
    bloodGroup: 'O+',
    organNeeded: 'Lung',
    medicalUrgency: 8,
    diseaseSeverity: 7,
    waitingTime: 30,
    compatibilityScore: 55,
    survivalProbability: 45,
    comorbidities: 5,
    organFailureStage: 4,
    infectionRisk: 'High',
    recoveryChance: 35,
    icuRequirement: 'Yes',
    donorMatchAvailability: 'Low',
    bmi: 28.9,
    hemoglobin: 9.5,
    creatinine: 3.0,
    bloodPressure: '155/98',
    oxygenSaturation: 85,
  },
];

// Add computed scores to sample patients
export const samplePatients = rawSamplePatients.map(patient => {
  const prediction = computeMLPrediction(patient);
  const sahpScore = computeSAHPScore(patient);
  const decision = computeDecision(patient);

  return {
    ...patient,
    priorityScore: prediction.priorityScore,
    priorityCategory: prediction.category,
    confidence: prediction.confidence,
    riskScore: prediction.riskScore,
    sahpScore,
    recommendation: decision.recommendation,
    status: prediction.priorityScore >= 75 ? 'High Priority' : 'Waiting',
    createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    analyzed: true,
  };
});

// Autofill sample for form
export const autofillPatient = {
  patientId: 'PT-NEW',
  name: 'Sample Patient',
  age: 47,
  gender: 'Male',
  bloodGroup: 'A+',
  organNeeded: 'Kidney',
  medicalUrgency: 8,
  diseaseSeverity: 7,
  waitingTime: 22,
  compatibilityScore: 75,
  survivalProbability: 65,
  comorbidities: 2,
  organFailureStage: 4,
  infectionRisk: 'Medium',
  recoveryChance: 60,
  icuRequirement: 'Yes',
  donorMatchAvailability: 'Medium',
  bmi: 25.5,
  hemoglobin: 11.0,
  creatinine: 4.2,
  bloodPressure: '142/88',
  oxygenSaturation: 95,
};
